# Generated by Django 4.0.6 on 2022-07-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('e_mail', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('pass_word', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TodoListIteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=50)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
    ]
