# Generated by Django 4.0.6 on 2022-07-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_uploadimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='caption',
        ),
    ]
