# Generated by Django 4.0.6 on 2022-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_todolistiteam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(default='', upload_to='myimage/'),
        ),
    ]
