# Generated by Django 4.0.6 on 2022-07-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistiteam',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
