# Generated by Django 4.0.6 on 2022-07-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_todolistiteam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistiteam',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
